/** @type {import('tailwindcss').Config} */
export default {
  important: true,
  content: [],
  theme: {
    screens: {
      mobile: { max: "500px" },
    },
    extend: {
      colors: {
        primary: "#409EFF",
        "primary-1": "#337ecc",
        "primary-2": "#79bbff",
        "primary-3": "#a0cfff",
        "primary-4": "#c6e2ff",
        "primary-5": "#d9ecff",
        "primary-6": "#ecf5ff",
        success: "#67C23A",
        "success-1": "#529b2e",
        "success-2": "#95d475",
        "success-3": "#b3e19d",
        "success-4": "#d1edc4",
        "success-5": "#e1f3d8",
        "success-6": "#f0f9eb",
        warning: "#E6A23C",
        "warning-1": "#b88230",
        "warning-2": "#eebe77",
        "warning-3": "#f3d19e",
        "warning-4": "#f8e3c5",
        "warning-5": "#faecd8",
        "warning-6": "#fdf6ec",
        danger: "#F56C6C",
        "danger-1": "#c45656",
        "danger-2": "#f89898",
        "danger-3": "#fab6b6",
        "danger-4": "#fcd3d3",
        "danger-5": "#fde2e2",
        "danger-6": "#fef0f0",
        info: "#909399",
        "info-1": "#73767a",
        "info-2": "#b1b3b8",
        "info-3": "#c8c9cc",
        "info-4": "#dedfe0",
        "info-5": "#e9e9eb",
        "info-6": "#f4f4f5",
      },
    },
  },
  plugins: [],
};
